### ISSUE TITLE
typescript version

### ISSUE THREAD

**Issue by pbrickell** [cmichaelgraham/aurelia-typescript-atom#4]
npm install hangs up on npm install typescript@Microsoft/TypeScript. Running this on ubuntu 15. All other dependencies install OK.

**Comment by cmichaelgraham** [comment]
can you try this?

``` bash
npm install -g typescript
```

if you want it local, just remove the `-g`

i believe that will give you ts15beta :+1:

**Comment by pbrickell** [comment]
Thanks, that gets it. I was just wondering why the very specific version in the package file.

Cheers.

**Comment by cmichaelgraham** [comment]
cool.  thanks :+1:
